# Generated by Django 5.0.4 on 2024-04-18 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NomeProduto', models.CharField(max_length=100)),
                ('Descricao', models.TextField(blank=True)),
                ('Preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Estoque', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.DeleteModel(
            name='ToDo',
        ),
    ]
